# Uncomment the next line to define a global platform for your project
# platform :ios, '12.0'

target 'swift-chat-v2-sample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for swift-chat-v2-sample
  pod 'KustomerChat', '~> 5.0.0'
  # UNCOMMENT THIS IF TESTING FROM BRANCH: pod 'KustomerChat', :git => 'https://github.com/kustomer/kustomer-ios.git', :branch => 'releases/5.0.0'
end
