# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'swift-chat-v2-sample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for swift-chat-v2-sample
  pod 'KustomerChat', '~> 3.1.0'
end
